name: Databricks Notebook Import

on:
  push:
    branches:
      - main
      - dev

jobs:
  import_notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Databricks CLI
      run: |
        pip install databricks-cli
        
    - name: Configure Databricks CLI
      env:
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_HOST: https://adb-6982357823576007.7.azuredatabricks.net/
      run: |
        printf "%s\n%s\n" "$DATABRICKS_TOKEN" "$DATABRICKS_HOST" | databricks configure --token
        
    - name: Import Notebooks to Databricks Workspace
      run: |
        databricks workspace import_dir notebooks/ /Repos/attauheed45@gmail.com/Databricks_demo/demo_folder/
